### ISSUE TITLE
no documentation / no react context example

### ISSUE THREAD

**Issue by Macilias** [patientslikeme/react-blockly-component#23]
Hi we do have a very hard time trying to use this component.
The provided example is written as a hmtl page and not used in react context.
Could you provide an example or a pointer to an example in context like react-boilerplate (https://github.com/react-boilerplate/react-boilerplate)

Thanks.

**Comment by nbudin** [comment]
This could certainly be better documented, but just to get you some help now: check https://github.com/patientslikeme/react-blockly-component/blob/master/src/dev-index.jsx, which is the JavaScript that that HTML page is loading.

**Comment by Macilias** [comment]
Hi nbudin, 
thats what I did. But I have bad luck using it that way:
https://github.com/Macilias/blockly-component-within-react-redux-boilerplate/blob/master/app/containers/BlocklyPage/BlocklyEditor.js

It seam not to be able to consume INITIAL_TOOLBOX_CATEGORIES because of missing toolboxCategories[0].type. Also not when the collection is stripped down to categories only (with type) as shown in INITIAL_TOOLBOX_CATEGORIES_EXT.

Can you help me out there?

**Comment by nbudin** [comment]
The thing with missing `toolboxCategories[0].type` is annoying but actually not the problem.  (It's a separate bug; `type` shouldn't be required for categories, only blocks.)

I downloaded your code and ran it, and Blockly does in fact appear to be rendering for me; however, it is invisible because the div is being set to 0px height.  I think this is because of some interaction between the boilerplate CSS and Blockly.  I would recommend you try removing all CSS from the page, and if that works, add it back bit by bit until you find the problematic part.

In any case, this is not a bug with react-blockly-component (since it's rendering fine, and setting the heights manually on elements in devtools does make things show up).  I'll write a separate bug for suppressing those propType warnings that shouldn't exist.

**Comment by nbudin** [comment]
Version 3.0.3 is now released with a fix for that warning you're seeing.  (As I mentioned above, this will not fix your problem, and there will still be warnings due to unknown tags - the unknown tag warnings aren't possible to fix from our end; maybe once https://github.com/google/blockly/issues/1978 is fixed.)  I still recommend trying the CSS fix I mentioned above.

**Comment by emreozdincer** [comment]
> This could certainly be better documented, but just to get you some help now: check https://github.com/patientslikeme/react-blockly-component/blob/master/src/dev-index.jsx, which is the JavaScript that that HTML page is loading.

You should really put this in the readme. Not fun to find out a solution digging through closed issues.
