### ISSUE TITLE
How do I include react blockly to my project?

### ISSUE THREAD

**Issue by yomi05** [patientslikeme/react-blockly-component#33]
I have included react-blockly-component to my project, I will like to know how to use it as I searched for examples but found none.

This is what I tried but got error:

import React from 'react';
import ReactBlocklyComponent from 'react-blockly-component';

const Blockly = () => {
  return (
    <div>
      <ReactBlocklyComponent />
    </div>
  );
};

export default Blockly;

**Comment by nbudin** [comment]
That definitely does look like an error.  There has to be _something_ inside those parentheses to return from your component; otherwise that's a JavaScript syntax error I think.

Here's an example: https://github.com/patientslikeme/react-blockly-component/blob/master/src/dev-index.jsx

There's more going on in there than you probably need for a starter component - for example, the `componentDidMount` method is not necessary for most real use cases and is only there to test that the toolbox is correctly updated when changed - but it does show how to render a Blockly editor with this.
