### ISSUE TITLE
Use with latest Blockly

### ISSUE THREAD

**Issue by mishoboss** [patientslikeme/react-blockly-component#7]
Hello, probably not a react-blockly-component issue, but when I try to use with latest Blockly from git, your component no longer finds `window.Blockly`. 

I mean like this:

```
https://raw.githubusercontent.com/google/blockly/master/blockly_compressed.js
https://raw.githubusercontent.com/google/blockly/master/blocks_compressed.js
```

Is there anything custom in these you use and why they work OK, but latest from git don't?

```
https://blockly-demo.appspot.com/static/blockly_compressed.js
https://blockly-demo.appspot.com/static/blocks_compressed.js
```

Also, any proper way to import Blockly with webpack?

Tried this, but it still didn't found it:

```
new webpack.ProvidePlugin({
    Blockly: "node-blockly"
  })
```

Any info is more than welcome.

**Comment by nbudin** [comment]
Hi @mishoboss!  Sorry to hear about the breakage.  I suspect Blockly has changed something about how it exposes the `Blockly` object in the latest version, so that it's no longer a direct child property of `window`.  I probably won't have time to look into it today, but if you're able to see how it's done in the latest releases of Blockly, that would be helpful.

As far as why the blockly-demo.appspot.com URLs still work, my guess would be they just haven't yet been updated with the newest git versions yet, so they'll probably break similarly in the future.

The webpack issue has eluded me for awhile.  Blockly uses the Google Closure compiler and a Python script as its build system, which doesn't seem to be compatible with the usual npm packaging workflow.  Various people have attempted to package Blockly in an npm-friendly way, including that `node-blockly` package you found, but the Blockly team at Google has stated it's not particularly interested in investing resources into maintaining this workflow, so as far as I can tell, the npm packages of Blockly mostly remain out-of-date most of the time, when they work at all, which isn't always.  That's why in my own projects that use this, I embed Blockly using a separate `<script>` tag.

**Comment by mishoboss** [comment]
Thanks for the quick answer. It's so sad Blockly is left behind in latest web trends. I'll try to investigate it tomorrow.

**Comment by mishoboss** [comment]
I'm unable to find something. I tried another approach. I tried to substitute`blockly_compressed.js` and `blocks_compressed.js` in `node-blockly` mofule with the files you use from demos. However I get `Uncaught TypeError: Cannot read property 'navigator' of undefined`, which means that `goog.global` is not defined. Any ideas why? :(

**Comment by nbudin** [comment]
If `goog.global` isn't defined, that sounds like the Closure standard library isn't being loaded... but I have no idea why. :(

**Comment by mishoboss** [comment]
Yes, seems like so. Or it breaks because of webpack for some reason. It's so pitty, because there is literally no alternative of Blockly out there. At least I'm not aware of some. :(

**Comment by benjie** [comment]
I believe this was a number of various bugs in `node-blockly` that have since been resolved. `node-blockly` is much more reliable now.

I think you can close this.

**Comment by benjie** [comment]
Oh, if you're using node-blockly you'll want to webpack it up and export it to global rather than using a second version of blockly; I use the following file, `blockly.js`:

```js
let Blockly;
if (typeof window !== 'undefined') {
  Blockly = require('node-blockly/browser-raw');
} else {
  Blockly = require('node-blockly/_blockly');
}
const blocklyJS = require('node-blockly/lib/javascript_compressed');
blocklyJS(Blockly);
module.exports = Blockly;
```

and then in my root I include it like:

```js
import Blockly from './blockly';

global.Blockly = Blockly;

...
```

**Comment by nbudin** [comment]
Thanks for the update @benjie!  I'm closing this since that does indeed seem like a much better solution.
