### ISSUE TITLE
Resizable Workspace

### ISSUE THREAD

**Issue by mishoboss** [patientslikeme/react-blockly-component#9]
How to make Blockly workspace be resizable? I tried to apply [this logic](https://developers.google.com/blockly/guides/configure/web/resizable), but it doesn't work. Seems size is applied on the next resize event.

**Comment by nbudin** [comment]
It should be simpler with react-blockly-component, since both components expose a `resize` function.  If you have a way of accessing the component, you should be able to simply call `.resize()` on it.  (If you're embedding the editor component in another component, you should be able to use a ref to access it and then call `this.refs.editor.resize()` or whatever you called the ref.)

**Comment by mishoboss** [comment]
Thanks, tried to call resize(), but still it doesn't resize. Any specific requirements for the parent element for this to work?

**Comment by mandalatv** [comment]
I’m experiencing the same problem. I have react-blockly-component placed in a parent div with 300px width. If I trigger the size of the parent div to change to 100% react-blockly-component doesn’t scale to the width unless I manually resize the browser.

I’ve attached a modified version of the example public/index.html to exhibit this problem. Despite BlocklyEditor containing a resize(), an error is thrown when a call is attempted. 

[index.txt](https://github.com/patientslikeme/react-blockly-component/files/952823/index.txt)
